### ISSUE TITLE
Orphaned locks are never released

### ISSUE THREAD

**Issue by sebsel** [whitfin/sleeplocks#3]
Currently, when a process requests a lock, and then crashes, the lock isn't released. At that point, no-one can obtain the lock anymore. With the phrase "It builds upon basic OTP principles", I was expecting this to be handled for us by Sleeplocks, but unfortunately it isn't.

Implementation would be as easy as to monitor all the PIDs that request a lock, so you receive messages about them being down (this is how supervisors under the hood work).

Happy to PR this. (In fact, I got it already working in a fork.)

**Comment by whitfin** [comment]
@sebsel I'm so sorry, I totally lost the thread on this - I have no idea how. I only noticed it because I was revisiting older repositories randomly. 

I saw you closed your PR, but I've manually merged it over, thank you for putting in the work there! Again, so sorry that this somehow got overlooked for so long 😞
